# Generated by Django 5.2.8 on 2026-01-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="optionvalue",
            name="hex_color",
        ),
    ]
