# Generated by Django 5.2.8 on 2026-01-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured"], name="app_product_is_feat_4b515b_idx"
            ),
        ),
    ]
