# Generated by Django 5.2.8 on 2026-01-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0002_product_is_featured_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="imagen_category",
            field=models.URLField(blank=True, null=True),
        ),
    ]
