# Generated by Django 5.2.3 on 2026-01-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0002_remove_optionvalue_hex_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="name",
            field=models.CharField(
                choices=[
                    ("Talla", "Talla"),
                    ("Color", "Color"),
                    ("Material", "Material"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
