# Generated by Django 5.2.3 on 2026-01-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0003_alter_option_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="name",
            field=models.CharField(
                choices=[
                    ("Color", "Color"),
                    ("Peso", "Peso"),
                    ("Medida", "Medida"),
                    ("Material", "Material"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
