# Generated by Django 5.2.8 on 2025-12-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0003_remove_product_image_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sales_count",
            field=models.IntegerField(default=0),
        ),
    ]
