# Generated by Django 5.2.8 on 2025-12-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0004_product_sales_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
