# Generated by Django 5.2.3 on 2026-01-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0004_alter_option_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="description",
            new_name="description_long",
        ),
        migrations.AddField(
            model_name="product",
            name="description_short",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty",
            field=models.TextField(blank=True),
        ),
    ]
