# Generated by Django 5.2.3 on 2026-01-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0005_rename_description_product_description_long_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="productvariant",
            name="app_product_sku_a5eadf_idx",
        ),
        migrations.RemoveIndex(
            model_name="productvariant",
            name="app_product_is_acti_b9c58a_idx",
        ),
        migrations.AlterField(
            model_name="option",
            name="name",
            field=models.CharField(
                choices=[
                    ("Color", "Color"),
                    ("Medida", "Medida"),
                    ("Peso", "Peso"),
                    ("Material", "Material"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
