# Generated by Django 5.2.3 on 2026-01-14 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Número de contacto del cliente", max_length=20
                    ),
                ),
                (
                    "department",
                    models.CharField(help_text="Departamento", max_length=100),
                ),
                ("city", models.CharField(help_text="Ciudad", max_length=100)),
                (
                    "neighborhood",
                    models.CharField(
                        blank=True, help_text="Barrio", max_length=100, null=True
                    ),
                ),
                (
                    "address",
                    models.CharField(help_text="Dirección principal", max_length=255),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones del pedido",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
