"""
Django settings for kalyzo project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
import logging
from pathlib import Path
from dotenv import load_dotenv
from django.core.management.utils import get_random_secret_key
from decouple import config
import dj_database_url

# Configurar logger
logger = logging.getLogger(__name__)

# --------------------------------------------
# BASE DIR & ENV
# --------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

SECRET_KEY = os.getenv("SECRET_KEY") or get_random_secret_key()

# --------------------------------------------
# DEBUG / PRODUCCIÓN
# --------------------------------------------
IS_PRODUCTION = os.getenv("RENDER_EXTERNAL_HOSTNAME") is not None
DEBUG = config('DEBUG', default=False, cast=bool)

# --------------------------------------------
# ALLOWED HOSTS
# --------------------------------------------

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

RENDER_EXTERNAL_HOSTNAME = os.getenv("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

if IS_PRODUCTION:
    ALLOWED_HOSTS.extend([
        'kalyzo.shop',
        'www.kalyzo.shop',
        '.onrender.com',
    ])

# SECURITY (PRODUCCIÓN)
if IS_PRODUCTION:
    CSRF_TRUSTED_ORIGINS = [
        'https://kalyzo.shop',
        'https://www.kalyzo.shop',
        'https://*.onrender.com',
    ]
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'


# --------------------------------------------
# APPLICATION DEFINITION
# --------------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "storages",
    "app_store",
    "app_products",
    "app_customers",
    "app_orders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware", 
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tienda_kalyzo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            "app_store/templates/app_store", 
            "app_products/templates/app_products", 
            "app_customers/templates/app_customers", 
            "app_orders/templates/app_orders"
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.static",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "app_store.context_processors.categorias_globales",
            ],
        },
    },
]

WSGI_APPLICATION = "tienda_kalyzo.wsgi.application"


# --------------------------------------------
# BASE DE DATOS
# --------------------------------------------
if IS_PRODUCTION:
    DATABASES = {
        'default': dj_database_url.config(
            default=os.getenv("DATABASE_URL"),
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }


# --------------------------------------------
# PASSWORD VALIDATION
# --------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# --------------------------------------------
# STATIC FILES
# --------------------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

if IS_PRODUCTION:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# --------------------------------------------
# MEDIA FILES - AWS S3
# --------------------------------------------
USE_S3 = IS_PRODUCTION

if USE_S3:
    try:
        AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
        AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
        AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
        AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME", default="us-east-2")
        
        if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_STORAGE_BUCKET_NAME:
            STORAGES = {
                "default": {
                    "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
                },
                "staticfiles": {
                    "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
                },
            }

            AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"
            MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"
            
            AWS_S3_OBJECT_PARAMETERS = {
                'CacheControl': 'max-age=86400',
            }
            
            # Sin ACL - Usa bucket policy en su lugar
            AWS_QUERYSTRING_AUTH = False
            AWS_DEFAULT_ACL = None
            AWS_S3_FILE_OVERWRITE = False
            AWS_S3_VERIFY = True
            
            logger.info("✅ AWS S3 configurado correctamente")
        else:
            raise ValueError("Credenciales de AWS incompletas")
            
    except Exception as e:
        logger.error(f"❌ Error configurando AWS S3: {e}")
        USE_S3 = False
        MEDIA_URL = "/media/"
        MEDIA_ROOT = BASE_DIR / "media"
else:
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"


# --------------------------------------------
# SECURITY (PRODUCCIÓN)
# --------------------------------------------
if IS_PRODUCTION:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'


# --------------------------------------------
# INTERNATIONALIZATION
# --------------------------------------------
LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True


# --------------------------------------------
# DEFAULT AUTO FIELD
# --------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --------------------------------------------
# ENCODING CONFIGURATION
# --------------------------------------------
DEFAULT_CHARSET = 'utf-8'
FILE_CHARSET = 'utf-8'
DEFAULT_CONTENT_TYPE = 'text/html; charset=utf-8'