# Generated by Django 5.2.3 on 2026-01-11 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_orders", "0001_initial"),
        (
            "app_products",
            "0006_remove_productvariant_app_product_sku_a5eadf_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CartReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=40)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_products.productvariant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["expires_at", "is_active"],
                        name="app_orders__expires_d7f698_idx",
                    )
                ],
                "unique_together": {("session_key", "variant")},
            },
        ),
    ]
